### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by jasperlachance** [oskar3123/StaffChat#4]
Installed this plugin to my BungeeCord server following the instructions (all two of them) and it's telling me I don't have permission to use that command when attempting to use any commands.

No information found on setting up permissions. **This plugin lacks the information it needs.**

**Comment by oskar3123** [comment]
You have to give yourself the correct permissions in the BungeeCord config https://www.spigotmc.org/wiki/bungeecord-configuration-guide/
Or you can use a permissions manager such as [BungeePerms](https://www.spigotmc.org/resources/bungeeperms.25/)

**Comment by jasperlachance** [comment]
Just a quick followup. It was an error on my part with the permissions. I set the permissions but I did not assign myself the admin group in that config. It's all working perfectly as expected now.

Sorry about that!

**Comment by oskar3123** [comment]
No problem, glad it's fixed now.
