### ISSUE TITLE
DiscordSRV Support

### ISSUE THREAD

**Issue by ghost** [oskar3123/StaffChat#5]
Hey, so i wanna have a channel in my discord that links the staffchat to a seperate channel. So i have a log of all the ingame staffchat messages. How would i go about doing that? Cuz i know in discordSRV u can set different channels. but idk what to put in the ingame one. As putting "StaffChat" doesn't work?

**Comment by oskar3123** [comment]
Sorry for a really late reply, I am gonna check if this is easy to add on my end.
